package controller;

public enum MenuType {
    ACCOUNT, MAINMENU, SHOP, BATTLE, HELP, COLLECTION, GRAVEYARD, START_NEW_GAME, SINGLE_GAME_MENU,
    MULTI_GAME_MENU, SINGLE_GAME_STORY_MODE, SINGLE_GAME_CUSTOM_MODE,CUSTOM_CARD_MENU
}
